= Лабораторна робота №6

== Введення-виведення(I/O). Файли. Виключення (Exceptions)

*Тема*: Розробка та реалізація програм із використанням класів для зберігання даних
та файлового введення-виведення.

*Мета роботи*: отримати навички створення та реалізації програм, що реалізують
операції введення-виведення із файлами.

== Завдання до лабораторної роботи

. Створити клас за завданням лабораторної роботи №2. Визначити метод, що
створює порожній масив об’єктів, з максимальною кількістю 100 елементів.

. Реалізувати зберігання даних у текстовий файл та зчитування з текстового файлу.
Враховувати можливість виникнення виключень, та обробляти їх, виводячи
відповідні повідомлення для користувача.

. Реалізувати зберігання даних у бінарний файл (за допомогою ObjectOutputStream)
та зчитування з бінарного файлу (за допомогою ObjectInputStream).

. Створити інтерактивне меню, за допомогою якого надати можливість
користувачеві виконувати додавання нових та вилучення існуючих елементів з
масивів, файлові операції введення-виведення та запити відповідно варіанту
завдання.

*Примітка*: всі операції виведення на екран повинні бути відокремлені від операцій пошуку та фільтрації даних. Для забезпечення такої поведінки рекомендується створити окремі класи для операцій екранного введення-виведення, файлового введення-виведення та бізнес-логіки застосування.


== Варіанти завдань
=== Варіант 1.

*Student:*  id, Прізвище, Ім'я, По батькові, Дата народження, Адреса, Телефон, Факультет, Курс, Група.

Створити колекцію об'єктів. Вивести:

..  список студентів заданого факультету;
..  список студентів, які народились після заданого року;
..  список навчальної групи в порядку алфавіту;
..  список студентів упорядкований за алфавітом назви факультету, а для студентів одного факультету – за датою народження

=== Варіант 2.

*Customer:*  id, Прізвище, Ім'я, По батькові, Дата народження, Адреса, Номер кредитної картки, Баланс рахунку (кількість грошей).

Створити колекцію об'єктів. Вивести:

..  список покупців, із вказаним іменем;
..  список покупців, у яких номер кредитної картки знаходиться в заданому інтервалі;
..  кількість та список покупців,  які мають заборгованість (від’ємний баланс на карті) в порядку зростання заборгованості;
..  список покупців, упорядкований за зростанням балансу рахунку, а при рівності балансів – за номером кредитної картки

=== Варіант 3.

*Patient:*  id, Прізвище, Ім'я, По батькові, Адреса, Телефон, Номер медичної карти, Діагноз.

Створити колекцію об'єктів. Вивести:

..  список пацієнтів, які мають указаний діагноз в порядку зростання номерів медичної картки;
..  список пацієнтів, номер медичної карти у яких знаходиться в заданому інтервалі;
..  кількість та список пацієнтів, номер телефона яких починається з вказаної цифри;
..  список діагнозів пацієнтів (без повторів) із вказанням кількості пацієнтів, що мають цей діагноз у порядку спадання цієї кількості

=== Варіант 4.

*Abiturient:* id, Прізвище, Ім'я, По батькові, Адреса, Телефон, Середній бал.

Створити колекцію об'єктів. Вивести:

..  список абітурієнтів із вказаним іменем, в порядку спадання середнього балу;
..  список абітурієнтів, середній бал у яких вище заданого;
..  вибрати задане число n абітурієнтів, що мають найвищий середній бал.
..  список абітурієнтів в порядку алфавіту за прізвищем, при збігу прізвищ – за іменами

=== Варіант 5.

*Book:*  id, Назва, Автор, Видавництво, Рік видання, Кількість сторінок, Ціна.

Створити колекцію об'єктів. Вивести:

..  список книг заданого автора в порядку зростання року  видання;
..  список книг, що видані заданим видавництвом;
..  список книг, що випущені після заданого року;
..  список авторів в алфавітному порядку

=== Варіант 6.

*House:* id, Номер квартири, Площа, Поверх, Кількість кімнат, Вулиця.

Створити колекцію об'єктів. Вивести:

..  список квартир, які мають задане число кімнат;
..  список квартир, які мають задане число кімнат та розташовані на поверсі, який знаходиться в заданому проміжку;
..  список квартир, які мають площу, що перевищує задану в порядку спадання площі. Якщо площа однакова – то в порядку зростання поверху;
..  список всіх квартир, в порядку зростання площі

=== Варіант 7.

*Phone:* id, Прізвище, Ім'я, По батькові, Номер рахунку, Час міських розмов, Час міжміських розмов.

Створити колекцію об'єктів. Вивести:

..  відомості про абонентів, у яких час міських розмов перевищує заданий;
..  відомості про абонентів, які користувались міжміським зв'язком в порядку алфавіту за прізвищем, при однакових прізвищах – за іменами, потім по-батькові;
..  відомості про абонентів чий номер рахунку знаходиться у вказаному діапазоні;
..  відомості про всіх абонентів в порядку зростання сумарного часу розмов


=== Варіант 8.

*Car:*  id, Модель, Рік випуску, Ціна, Реєстраційний номер.

Створити колекцію об'єктів. Вивести:

..  список автомобілів заданої моделі в порядку зростання року випуску;
..  список автомобілів заданої моделі, які експлуатуються більше n років;
..  список автомобілів заданого року випуску, ціна яких більше вказаної;
..  список автомобілів в порядку спадання ціни. Якщо ціна однакова, то в порядку зростання року випуску

=== Варіант 9.

*Product:* id, Найменування, Виробник, Ціна, Термін зберігання, Кількість.

Створити колекцію об'єктів. Вивести:

..  список товарів для заданого найменування в порядку спадання терміну зберігання;
..  список товарів для заданого найменування, ціна яких не перевищує задану;
..  список товарів, термін зберігання яких більше заданого;
..  список товарів, впорядкований за зростанням вартості (кількість * ціна), якщо вартість однакова, то за спаданням ціни


=== Варіант 10.

*Train:* id, Пункт призначення, Номер поїзду, Час відправки, Число місць (загальних, купе, плацкарт, люкс).

Створити колекцію об'єктів. Вивести:

..  список поїздів, які прямують до заданого пункту призначення в порядку зростання часу відправки, якщо час однаковий – за зростанням номеру поїзда;
..  список поїздів, які прямують до заданого пункту призначення та відправляються після заданої години;
..  список поїздів, які відправляються до заданого пункту призначення та мають загальні місця;
..  список поїздів, які відправляються до заданого пункту призначення в порядку зростання кількості всіх місць

